### ISSUE TITLE
References to "DevExpress"

### ISSUE THREAD

**Issue by wizhi** [LaurenzG/Linodo#2]
As stated in the [README](https://github.com/LaurenzG/Linodo/blob/40c209799570abca305a68f1a5260b48ea048996/README.md), there currently exists [references](https://github.com/LaurenzG/Linodo/blob/40c209799570abca305a68f1a5260b48ea048996/LightNovelDownloader/WpfLightNovelClient/WpfLightNovelClient.csproj#L56) to [DevExpress](https://www.devexpress.com/) specific assemblies, which aren't actually in use.

**Comment by LaurenzG** [comment]
Thanks for taking your time to sort out those issues!
